spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5671}
    username: ${RABBIT_USER:appuser}
    password: ${RABBIT_PASSWORD:admin123}
    ssl:
      enabled: true

video:
  api:
    url: ${VIDEO_API_URL:http://localhost:8082/api/videos}
