apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
  namespace: hackathon-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      serviceAccountName: worker-service-account
      containers:
      - name: video-processor
        image: 239409137076.dkr.ecr.us-east-1.amazonaws.com/worker:TAG
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: video-processor-config
        env:
        - name: RABBIT_PASSWORD
          value: 'V2f440#PBD-JYkom+'
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
