apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: hackathon-video-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::239409137076:role/hackathon-fiapx-app-role
