apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: video-processor-secret
  namespace: hackathon-video-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secretsmanager
    kind: ClusterSecretStore
  target:
    name: video-processor-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "rds!db-051612da-a9be-4c36-a343-f9261a18f529-lrkPVU"
        property: password
    - secretKey: RABBIT_PASSWORD
      remoteRef:
        key: "fiapx-rabbitmq-v6-password-v6"
        property: password
