apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: video-processor-secret
  namespace: hackathon-worker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secretsmanager
    kind: ClusterSecretStore
  target:
    name: video-processor-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBIT_PASSWORD
      remoteRef:
        key: "fiapx-rabbitmq-v6-password-v6"
